### Post Request to create a Patient

POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Jainam Rupani",
    "email": "rupani@gmail.com",
    "address": "Abhiyanta Colony Ramnagar Chandrapur",
    "dateOfBirth": "2003-10-04",
    "registeredDate": "2025-12-14"
}

###